name: toucan_conda_venv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - attrs=21.2.0
  - audioread=2.1.9
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.14.6
  - charset-normalizer=2.0.4
  - clean-text=0.3.0
  - colorama=0.4.4
  - cryptography=36.0.0
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - cython=0.29.25
  - dbus=1.13.18
  - decorator=5.1.0
  - editdistance=0.5.3
  - emoji=1.6.1
  - expat=2.4.1
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - fribidi=1.0.10
  - ftfy=5.8
  - future=0.18.2
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - graphviz=2.42.3
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=2.8.1
  - icu=58.2
  - idna=3.3
  - intel-openmp=2021.4.0
  - isodate=0.6.0
  - joblib=1.1.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libffi=3.3
  - libflac=1.3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libllvm11=11.1.0
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.37
  - librosa=0.8.1
  - libsndfile=1.0.31
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvorbis=1.3.7
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - llvmlite=0.37.0
  - lz4-c=1.9.3
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - numba=0.54.1
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pango=1.42.4
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.2.4
  - pixman=0.40.0
  - pooch=1.4.0
  - progressbar=2.5
  - pycparser=2.21
  - pydub=0.25.1
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pysocks=1.7.1
  - pysoundfile=0.10.3.post1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-graphviz=0.16
  - python_abi=3.8
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - pyyaml=6.0
  - qt=5.9.7
  - readline=8.1
  - requests=2.26.0
  - resampy=0.2.2
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - tabulate=0.8.9
  - tbb=2021.3.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - torchaudio=0.10.0
  - torchvision=0.11.1
  - tornado=6.1
  - tqdm=4.62.3
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - unicodecsv=0.14.1
  - unidecode=1.2.0
  - uritemplate=4.1.1
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - wheel=0.37.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.2
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - argparse==1.4.0
    - auraloss==0.2.1
    - clldutils==3.10.1
    - colorlog==6.6.0
    - commonmark==0.9.1
    - csvw==1.11.0
    - dlinfo==1.2.1
    - huggingface-hub==0.2.1
    - hyperpyyaml==1.0.0
    - phonemizer==3.0.1
    - pygments==2.10.0
    - pyloudnorm==0.1.0
    - pyworld==0.3.0
    - regex==2021.11.10
    - rfc3986==1.5.0
    - rich==9.10.0
    - ruamel-yaml==0.17.19
    - ruamel-yaml-clib==0.2.6
    - segments==2.2.0
    - sentencepiece==0.1.96
    - sounddevice==0.4.3
    - speechbrain==0.5.11
    - torch-complex==0.2.1
    - torchviz==0.0.2
    - unsilence==1.0.8
